/**
 * Codebase Map (Auto-generated)
 * Generated by update_map.py
 * DO NOT EDIT MANUALLY
 */
export const CODEBASE_MAP = {
  "template-to-follow": [],
  "elements": [
    {
      "name": "APP_INFO",
      "file": "scripts/app.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Metadata object for the main application orchestrator.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "APP"
      ]
    },
    {
      "name": "TEST_UPDATE_VARIABLE",
      "file": "scripts/app.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Metadata object for the main application orchestrator.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "APP"
      ]
    },
    {
      "name": "handleBreadcrumbClick",
      "file": "scripts/app.js",
      "type": "function",
      "signature": "(facet, index) => void",
      "description": "",
      "categories": [
        "APP"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "handleRestart",
      "file": "scripts/app.js",
      "type": "function",
      "signature": "() => void",
      "description": "",
      "categories": [
        "APP"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "handleSelection",
      "file": "scripts/app.js",
      "type": "function",
      "signature": "(facet, value) => void",
      "description": "",
      "categories": [
        "APP"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "init",
      "file": "scripts/app.js",
      "type": "function",
      "signature": "() => void",
      "description": "",
      "categories": [
        "APP"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "updateUI",
      "file": "scripts/app.js",
      "type": "function",
      "signature": "() => void",
      "description": "",
      "categories": [
        "APP"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "CONSTANTS_INFO",
      "file": "scripts/constants.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Object containing definitions for each facet, including labels and icons.",
      "categories": [
        "CONSTANTS"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "FACET_DEFINITIONS",
      "file": "scripts/constants.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Object containing definitions for each facet, including labels and icons.",
      "categories": [
        "CONSTANTS"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "FACET_ORDER",
      "file": "scripts/constants.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Object containing definitions for each facet, including labels and icons.",
      "categories": [
        "CONSTANTS"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "FIELD_MAP",
      "file": "scripts/constants.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Object mapping UI facet names to product catalog field names.",
      "categories": [
        "CONSTANTS"
      ],
      "dependencies": [],
      "sideEffects": false
    },
    {
      "name": "applyFilters",
      "file": "scripts/logic.js",
      "type": "function",
      "signature": "(selections, catalog) => void",
      "description": "Filters the product catalog based on user selections.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "FACET",
        "LOGIC"
      ]
    },
    {
      "name": "calculateNextSelections",
      "file": "scripts/logic.js",
      "type": "function",
      "signature": "(current, facet, value) => void",
      "description": "Calculates the next selection state after a user choice.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "FACET",
        "LOGIC"
      ]
    },
    {
      "name": "getProductField",
      "file": "scripts/logic.js",
      "type": "function",
      "signature": "(product, uiFacet) => void",
      "description": "Calculates the next selection state after a user choice.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "FACET",
        "LOGIC"
      ]
    },
    {
      "name": "getUniqueOptions",
      "file": "scripts/logic.js",
      "type": "function",
      "signature": "(attribute, products) => void",
      "description": "Runs the facet selection loop to determine next questions or final products.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "FACET",
        "LOGIC"
      ]
    },
    {
      "name": "runFacetLoop",
      "file": "scripts/logic.js",
      "type": "function",
      "signature": "(selections) => void",
      "description": "Runs the facet selection loop to determine next questions or final products.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "FACET",
        "LOGIC"
      ]
    },
    {
      "name": "BASE_PRODUCT_URL",
      "file": "scripts/productCatalog.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Array of product objects for the catalog.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "DATA"
      ]
    },
    {
      "name": "PRODUCT_CATALOG",
      "file": "scripts/productCatalog.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Array of product objects for the catalog.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "DATA"
      ]
    },
    {
      "name": "addChatMessage",
      "file": "scripts/ui/chat.js",
      "type": "function",
      "signature": "(text, type, icon = 'fa-comment') => void",
      "description": "Adds a chat message bubble to the chat interface.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI",
        "CHAT"
      ]
    },
    {
      "name": "renderChat",
      "file": "scripts/ui/chat.js",
      "type": "function",
      "signature": "(selections, engineResult) => void",
      "description": "Renders the chat interface with messages based on selections and engine results.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI",
        "CHAT"
      ]
    },
    {
      "name": "createOptionCard",
      "file": "scripts/ui/components.js",
      "type": "function",
      "signature": "(facet, value, onSelect, selections = {}) => void",
      "description": "Creates a DOM card element for a facet option with image and click handling.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "createProductCard",
      "file": "scripts/ui/components.js",
      "type": "function",
      "signature": "(product) => void",
      "description": "Creates a DOM card element displaying product details with actions.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "getIconForValue",
      "file": "scripts/ui/components.js",
      "type": "function",
      "signature": "(facet, value) => void",
      "description": "Creates a DOM card element for a facet option with image and click handling.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "breadcrumbEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat tab button.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "chatMessagesEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "chatSidebar",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "gridEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the wizard tab button.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "productResultsEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "restartBtn",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "resultAreaEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the wizard column container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "tabChat",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "tabWizard",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "titleEl",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat messages container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "wizardColumn",
      "file": "scripts/ui/elements.js",
      "type": "constant",
      "signature": "N/A",
      "description": "DOM element for the chat sidebar container.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "UI_INFO",
      "file": "scripts/ui/index.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Metadata object for the UI module.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "renderBreadcrumbs",
      "file": "scripts/ui/navigation.js",
      "type": "function",
      "signature": "(selections, onReset) => void",
      "description": "Renders breadcrumb navigation from current selections.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "switchTab",
      "file": "scripts/ui/navigation.js",
      "type": "function",
      "signature": "(tab) => void",
      "description": "Switches between wizard and chat tabs in mobile view.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "initEventListeners",
      "file": "scripts/ui/renderer.js",
      "type": "function",
      "signature": "(callbacks) => void",
      "description": "Initializes all event listeners for UI interactions.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "updateView",
      "file": "scripts/ui/renderer.js",
      "type": "function",
      "signature": "(selections, engineResult, callbacks) => void",
      "description": "Updates the entire view based on selections and engine results.",
      "dependencies": [],
      "sideEffects": false,
      "category": "Uncategorized",
      "categories": [
        "UI"
      ]
    },
    {
      "name": "logger",
      "file": "scripts/utils/logger.js",
      "type": "constant",
      "signature": "N/A",
      "description": "Structured console logger providing grouped, labeled, and styled console logs with caller identification",
      "dependencies": [],
      "sideEffects": false,
      "category": "",
      "categories": [
        "UTILS"
      ]
    }
  ]
};
